openapi: 3.0.3
info:
  title: 'Malingo api documentation'
  description: "This api documentation contains all the endpoints for the malingo project. \n    a platform where you can effortlessly find companions for your next adventure, be it a travel buddy,\n     a dining partner, or someone to join you for a stroll or a random conversation. Malingo is a solution\n      that enables individuals to connect, share experiences, and foster new relationships while splitting\n       costs or covering expenses as agreed.\n    "
  version: 1.0.0
servers:
  -
    url: 'https://rrn24.techchantier.com/malingo/public/api'
paths: []
tags: []
